# # print("helllow world")

# a = int(input("Enter a Number"))

# print(a)



# a = int(input("Enter a First Number : "))
# b = int(input("Enter a Second Number : "))

# print(a+b)

# a = float(input("Enter a Number : "))

# area = 3.14 * a * a

# print(area)


# a = int(input("Enter a number : "))

# if a%2==0:
#     print("Enven Number")

# else:
#     print("Odd number")

a = int(input("Enter Fisrt Number : "))
b = int(input("Enter Second Number : "))
c = int(input("Enter third Number : "))

if a>b and a>c:
    print(a)
elif b>a and b>c:
    print(b)
elif c>a and c>b:
    print(c)

else:
    print("The Number is Zero")





